---
tenants:
  # Definition of tenants. Additional level of abstraction to VRFs
  - name: PROD
    # Number used to generate the VNI of each VLAN by adding the VLAN number in this tenant.
    mac_vrf_vni_base: 10000

    # List of BGP peer groups definitions.
    # This will configure BGP peer groups to be used inside the tenant VRF for peering with external devices.
    # Since BGP peer groups are configured at higher BGP level, shared between VRFs,
    # peer_group names should not overlap between VRFs.
    bgp_peer_groups:

        # BGP peer group name.
      - name: PROD-PALO

        # Nodes is required to restrict configuration of BGP neighbors to certain nodes in the network.
        # If not set the peer-group is created on devices which have a bgp_peer mapped to the corresponding peer_group.
        nodes:
          - dc1-leaf2a
        address_family_ipv4:
          activate: true

          # # Inbound route-map name.
          # route_map_in: <str>

          # # Outbound route-map name.
          # route_map_out: <str>
          # default_originate:
          #   always: <bool>

          #   # Route-map name.
          #   route_map: <str>
          # next_hop:
        #     address_family_ipv6:
        #       enabled: <bool; required>
        #       originate: <bool>
        #     # This key is deprecated.
        #     # Support will be removed in AVD version 5.0.0.
        #     # Use <samp>address_family_ipv6</samp> instead.
        #     address_family_ipv6_originate: <bool>

        #   # Inbound prefix-list name.
        #   prefix_list_in: <str>

        #   # Outbound prefix-list name.
        #   prefix_list_out: <str>
        # address_family_ipv6:
        #   activate: <bool>

          # Inbound route-map name.
          route_map_in: <str>

          # Outbound route-map name.
          route_map_out: <str>

          # Inbound prefix-list name.
          prefix_list_in: <str>

          # Outbound prefix-list name.
          prefix_list_out: <str>

        # Key only used for documentation or validation purposes.
        type: Inter-VRF Inspection

        # BGP AS <1-4294967295> or AS number in asdot notation "<1-65535>.<0-65535>".
        # For asdot notation in YAML inputs, the value must be put in quotes, to prevent it from being interpreted as a float number.
        remote_as: 64512

        # BGP AS <1-4294967295> or AS number in asdot notation "<1-65535>.<0-65535>".
        # For asdot notation in YAML inputs, the value must be put in quotes, to prevent it from being interpreted as a float number.
        local_as: 65000
        description: VRF-PROD ASN
        shutdown: false
        # BGP AS-PATH options.
        # as_path:

          # Replace AS number with local AS number.
          remote_as_replace_out: true

        #   # Disable prepending own AS number to AS path.
        #   prepend_own_disabled: <bool>

        # # Remove private AS numbers in outbound AS path.
        # remove_private_as:
        #   enabled: <bool>
        #   all: <bool>
        #   replace_as: <bool>
        # remove_private_as_ingress:
        #   enabled: <bool>
        #   replace_as: <bool>

        # # Peer-filter name.
        # # note: `bgp_listen_range_prefix` and `peer_filter` should not be mixed with
        # # the new `listen_ranges` key above to avoid conflicts.
        # # This key is deprecated.
        # # Support will be removed in AVD version 5.0.0.
        # # Use <samp>listen_ranges</samp> instead.
        # peer_filter: <str>
        # next_hop_unchanged: <bool>

        # # IP address or interface name.
        # update_source: <str>
        # route_reflector_client: <bool>

        # # Enable BFD.
        # bfd: <bool>

        # # Override default BFD timers. BFD must be enabled with `bfd: true`.
        # bfd_timers:

        #   # Interval in milliseconds.
        #   interval: <int; 50-60000; required>

        #   # Rate in milliseconds.
        #   min_rx: <int; 50-60000; required>
        #   multiplier: <int; 3-50; required>

        # Time-to-live in range of hops.
        ebgp_multihop: 3
        # next_hop_self: <bool>
        # password: <str>
        # passive: <bool>
        # default_originate:
        #   enabled: <bool>
        #   always: <bool>

        #   # Route-map name.
        #   route_map: <str>

        # 'all' or a combination of 'standard', 'extended', 'large' and 'link-bandwidth (w/options)'.
        send_community: all

        # Maximum number of routes (0 means unlimited).
        maximum_routes: 12000


    vrfs:
      # VRF definitions inside the tenant.
      - name: PROD
        # VRF VNI definition.
        vrf_vni: 10
        # Enable VTEP Network diagnostics
        # This will create a loopback with virtual source-nat enable to perform diagnostics from the switch.
        vtep_diagnostic:
          # Loopback interface number
          loopback: 10
          # Loopback ip range, a unique ip is derived from this ranged and assigned
          # to each l3 leaf based on it's unique id.
          loopback_ip_range: 10.255.10.0/27
        svis:
          # SVI definitions.
          - id: 11
            # SVI Description
            name: PROD_VLAN11
            enabled: true
            # IP anycast gateway to be used in the SVI in every leaf.
            ip_address_virtual: 10.10.11.1/24
          - id: 12
            name: PROD_VLAN12
            enabled: true
            ip_address_virtual: 10.10.12.1/24
          - id: 21
            name: PROD_VLAN21
            enabled: true
            ip_address_virtual: 10.10.21.1/24
          - id: 22
            name: PROD_VLAN22
            enabled: true
            ip_address_virtual: 10.10.22.1/24
          - id: 1000
            name: PROD_FW_TRANSIT
            enabled: true
            ip_address_virtual: 10.254.254.1/24
        bgp_peers:
          ip_address: 10.254.255.1
          peer_group: PROD-PALO
          local_as: 65000
          update_source: loopback10

    l2vlans:
      # These are pure L2 vlans. They do not have a SVI defined in the l3leafs and they will be bridged inside the VXLAN fabric
      - id: 3401
        name: L2_VLAN3401
      - id: 3402
        name: L2_VLAN3402

  - name: QA
    # Number used to generate the VNI of each VLAN by adding the VLAN number in this tenant.
    mac_vrf_vni_base: 11000
    vrfs:
      # VRF definitions inside the tenant.
      - name: QA
        # VRF VNI definition.
        vrf_vni: 12
        # Enable VTEP Network diagnostics
        # This will create a loopback with virtual source-nat enable to perform diagnostics from the switch.
        vtep_diagnostic:
          # Loopback interface number
          loopback: 12
          # Loopback ip range, a unique ip is derived from this ranged and assigned
          # to each l3 leaf based on it's unique id.
          loopback_ip_range: 10.255.12.0/27
        svis:
          # SVI definitions.
          - id: 13
            # SVI Description
            name: QA_VLAN11
            enabled: true
            # IP anycast gateway to be used in the SVI in every leaf.
            ip_address_virtual: 10.11.11.1/24
          - id: 14
            name: QA_VLAN12
            enabled: true
            ip_address_virtual: 10.11.12.1/24
          - id: 23
            name: QA_VLAN21
            enabled: true
            ip_address_virtual: 10.11.21.1/24
          - id: 24
            name: QA_VLAN22
            enabled: true
            ip_address_virtual: 10.11.22.1/24
          - id: 1001
            name: QA_FW_TRANSIT
            enabled: true
            ip_address_virtual: 10.254.253.1/24

    l2vlans:
      # These are pure L2 vlans. They do not have a SVI defined in the l3leafs and they will be bridged inside the VXLAN fabric
      - id: 3403
        name: L2_VLAN3403
      - id: 3404
        name: L2_VLAN3404

  - name: SHAREDSVCS
    # Number used to generate the VNI of each VLAN by adding the VLAN number in this tenant.
    mac_vrf_vni_base: 12000
    vrfs:
      # VRF definitions inside the tenant.
      - name: SHAREDSVCS
        # VRF VNI definition.
        vrf_vni: 14
        # Enable VTEP Network diagnostics
        # This will create a loopback with virtual source-nat enable to perform diagnostics from the switch.
        vtep_diagnostic:
          # Loopback interface number
          loopback: 14
          # Loopback ip range, a unique ip is derived from this ranged and assigned
          # to each l3 leaf based on it's unique id.
          loopback_ip_range: 10.255.14.0/27
        svis:
          # SVI definitions.
          - id: 15
            # SVI Description
            name: SHAREDSVCS_VLAN11
            enabled: true
            # IP anycast gateway to be used in the SVI in every leaf.
            ip_address_virtual: 10.12.11.1/24
          - id: 16
            name: SHAREDSVCS_VLAN12
            enabled: true
            ip_address_virtual: 10.12.12.1/24
          - id: 25
            name: SHAREDSVCS_VLAN21
            enabled: true
            ip_address_virtual: 10.12.21.1/24
          - id: 26
            name: SHAREDSVCS_VLAN22
            enabled: true
            ip_address_virtual: 10.12.22.1/24
          - id: 1002
            name: SHAREDSVCS_FW_TRANSIT
            enabled: true
            ip_address_virtual: 10.254.252.1/24

    l2vlans:
      # These are pure L2 vlans. They do not have a SVI defined in the l3leafs and they will be bridged inside the VXLAN fabric
      - id: 3405
        name: L2_VLAN3405
      - id: 3406
        name: L2_VLAN3406
